### ISSUE TITLE
is it possible to save ravage status? hunger and thirst?

### ISSUE THREAD

**Issue by xzagrx** [gruppe-adler/grad-persistence#16]
Hello Adler, i would like to know is it possible to save ravage hunger and thrist status? if yes how to do that? should i do that via custom variables?

**Comment by McDiod** [comment]
Yes, do it via custom variables. I just checked the Ravage code, the variable names are:

* "thirst"
* "hunger"
* "radiation"
* "radTriggers"
* "status"
* "rad_status"

(Yes, really, no prefix). They are all saved on the `player`. Saving `radTriggers` probably makes no sense, all others should be fine. Here is an example:

```sqf
class CfgGradPersistence {
    class customVariables {
        class ravageHunger {
            varName = "hunger";
            varNamespace = "player";
            public = 1;
        };
    };
};
```

**Comment by xzagrx** [comment]
hm, well i did as you told me, place the example into description and it's dosen't work
`    class customVariables {
        class ravageHunger {
            varName = "hunger";
            varNamespace = "player";
            public = 1;
        };
        class ravageThirst {
            varName = "thirst";
            varNamespace = "player";
            public = 1;
        };
    };
};
`
there is no errors in my RPT file about that, maybe i'm doing something wrong?

**Comment by McDiod** [comment]
Is this multiplayer? Dedicated server?

**Comment by xzagrx** [comment]
Dedicated server

**Comment by McDiod** [comment]
The server probably doesn't know about those variables, see here:
https://github.com/gruppe-adler/grad-persistence/wiki/saving-variables#limitations

I might add a feature for player-local variables at some point, but for now the easiest workaround would be to use the config as above and then add this to `initPlayerLocal.sqf`:

```sqf
// broadcast player status vars every 2s for grad-persistence
[{
    {
        player setVariable [_x select 0, player getVariable _x,true];
    } forEach [
        // delete the ones you don't need
        ["thirst", 100],
        ["hunger", 100],
        ["radiation", 0],
        ["status", "<t size='1.17' align='right' color='#30C730'>Healthy</t>"],
        ["rad_status", ""]
    ];
},2,[]] call CBA_fnc_addPerFrameHandler;
```

**Comment by xzagrx** [comment]
still not working :( so... i think this is might be a bug :(

**Comment by lsvalmont** [comment]
Hey McDiod, while you are fixing the custom variables it might be worth looking at the way BIS save stores all the variables automatically without having to specify each one, one by one. Perhaps it could be a neat solution/option for less experienced mission makers or for missions with too many variables like mine. Also perhaps using this command **allVariables** to get all variables and saving their values at different time intervals. 
Anyways, keep up the amazing job!

**Comment by McDiod** [comment]
Should be fixed in [0.7.1](https://github.com/gruppe-adler/grad-persistence/releases/tag/0.7.1). Existing saves will still not work, but new saves should be fine. Please report back.

**Comment by xzagrx** [comment]
okay, gonna test the new version now, i'll tell you if it's worked or not.

**Comment by xzagrx** [comment]
0.7.1 is working now, thanks for your work and last question before you close the issue, is it possible to make add-action on vehicles and ammoboxes to save its position and content so players can save it manualy without admin using command?

**Comment by McDiod** [comment]
Not possible without some major changes. You can only save all objects of one category at once. You could of course use an addAction for that if you are not worried about the server lag it might create every time a player uses the action.

**Comment by xzagrx** [comment]
okay thanks
