### ISSUE TITLE
undefined Variable GRAD_persistence_fnc_saveMission

### ISSUE THREAD

**Issue by AxeriusNetwork** [gruppe-adler/grad-persistence#17]
Picture: https://gyazo.com/c23fb5149d8dfe834794438507d7f7bc

Error Code: 
`  4:13:22 Error in expression <e {true} do {
sleep 10;
[true, 10] call grad_persistence_fnc_saveMission;
diag_l>
 4:13:22   Error position: <grad_persistence_fnc_saveMission;
diag_l>
 4:13:22   Error Undefined variable in expression: grad_persistence_fnc_savemission
 4:13:22 File C:\Users\Jack\Documents\Arma 3 - Other Profiles\Lt%2e%20Capwell\mpmissions\EC_Training.hebontes\initServer.sqf, line 5`

initServer.sqf Code: 
`while {true} do {
	sleep 10;
    [true, 10] call grad_persistence_fnc_saveMission;
    diag_log "Server persistance has been saved.";
};`

**Comment by McDiod** [comment]
This sounds like the functions are not properly included in `cfgFunctions`. Double check:

https://github.com/gruppe-adler/grad-persistence/wiki/Installation
