### ISSUE TITLE
Fuel

### ISSUE THREAD

**Issue by KappyTheLimey** [gruppe-adler/grad-persistence#18]
Hello,

Extremely happy to see someone working on a persistence system! I have followed the wiki and have a temp mission setup, the problem however is that the vehicle fuel levels reset when the mission is saved through admin and reloaded after a server restart. Is there something I am missing?

**Comment by McDiod** [comment]
Hi, 
it looks like saving fuel is not a feature yet, not sure how I missed that 😅. Will be added in next realease I guess.

**Comment by KappyTheLimey** [comment]
Cheers for the hard work!

**Comment by McDiod** [comment]
Added in [0.7.2](https://github.com/gruppe-adler/grad-persistence/releases/tag/0.7.2).
