### ISSUE TITLE
player loading with respawn template "MenuPosition"

### ISSUE THREAD

**Issue by Oldru** [gruppe-adler/grad-persistence#22]
I'm making a Ravage mission for my group and me to play. well, because I'm stubborn and don't want to do personal boxes/lockers for everyone I wanted to use this. I have the description set up to save the player's inventory but not the position and to not save the damage either.

Attached are both the ravage mission and a modeless mission with all the same scripts (none are mod dependent) also attached is an HTML file in which you can drag to your ARMA launcher if you would like to test the "bug" on to see if it is a mission issue

[New WinRAR ZIP archive.zip](https://github.com/gruppe-adler/grad-persistence/files/3877164/New.WinRAR.ZIP.archive.zip)

**Comment by Oldru** [comment]
also sorry for it being a WinRAR archive I had to use it for a bit to easier pack and unpack the zip files

**Comment by McDiod** [comment]
I only had a look at the `player inventory save test` mission. The problem is this:

1. mission starts
2. player inventory is loaded
3. player selects spawn position from respawn menu
4. player unit respawns and resets loadout

What you can do is add this to your `onPlayerRespawn.sqf`:

```sqf
if (missionNamespace getVariable ["oldru_isFirstRespawn",true]) then {
    oldru_isFirstRespawn = false;
    [] call grad_persistence_fnc_requestLoadPlayer;
};
```

**Comment by Oldru** [comment]
Ok, I tested it and it works. that was kinda a stupid thing on my part, I knew about the whole spawns the character so you can select a spawn. but it didn't even cross my mind that it was resetting the inventory.

ok, so for my next question is will I have to do this for every playable character, in case you haven't already facepalmed already. I am Somewhat new to scripting in ARMA.

**Comment by McDiod** [comment]
> for every playable character

Are you using playable units that will be sometimes controlled by players, sometimes by AI? So for example your mission has 6 slots and if there are only 4 players, the remaining 2 will be AI? In that case I don't know how grad-persistence will handle it. My guess is "not well".

If the above is not what you are talking about, then the answer is no, the script bit that I posted is not something that needs to be done per unit. The script file `onPlayerRespawn.sqf` is executed locally on the machine of the player that just respawned. The variable `oldru_isFirstRespawn` is only local as well, so if one player respawns for the first time, he will set it to `false`, but on every other machine it is still undefined (which is the same as `true` here).

See also:
https://community.bistudio.com/wiki/Event_Scripts
https://community.bistudio.com/wiki/Multiplayer_Scripting

**Comment by Oldru** [comment]
Ok so I don't have to do that for everyone. And when I say playable charaters I'm just refering to the character. Because I set up my ravage with everyone separate and if I was to allow So then they would just stand there, unless someone shot at them of course. Anyway thank you for the help. If I am able to get arma to let me host a server again then I will fully test that and let you know if I have any further issues.
