### ISSUE TITLE
AceX food/water peristence

### ISSUE THREAD

**Issue by Pyth3rEx** [gruppe-adler/grad-persistence#24]
Hey, I would like to know if this was tested/possible using this mod.

**Comment by Pyth3rEx** [comment]
So I tried a few things but sadly still can't figure it out. I'm trying to get aceX food/water + ace medical and that's what I came up with?
`	class customVariables {
        class acexFood {
            varName = "QGVAR(hunger)";
            varNamespace = "player";
            public = 0;
        };
		class acexWater {
            varName = "QGVAR(thirst)";
            varNamespace = "player";
            public = 0;
        };
		class aceDamage {
            varName = "[QEGVAR(medical,lastDamageSource)";
            varNamespace = "unit";
            public = 0;
        };
		class acePain {
            varName = "GET_PAIN(_unit)";
            varNamespace = "unit";
            public = 0;
        };
    };`

**Comment by McDiod** [comment]
This should work in theory, but you will have to either `#include` ACE's/ACEX's macros, or resolve the variables yourself. For example once the preprocessor is done with it `QGVAR(hunger)` becomes `acex_field_rations_hunger`, as the respective [script_component.hpp](https://github.com/acemod/ACEX/blob/11234b8a925372bf98e1fd2347533068fec2763f/addons/field_rations/script_component.hpp#L1) tells us.

```
class acexFood {
    varName = "acex_field_rations_hunger";
    varNamespace = "player";
    public = 0;
};
```

You will also have to test and make sure that these variables are not loaded before they are initialized by ACE/ACEX.

**Comment by Pyth3rEx** [comment]
I'm really confused by a lot of things you said (most likely because I don't understand these things?). So do I just need to paste that piece of code in the description.ext instead of what I've done?
Thanks

**Comment by McDiod** [comment]
You have to look up what `GVAR(variable)` actually means. In ACEX it means `acex_COMPONENT_variable`, so because the hunger variable is part of the field_rations component, `GVAR(hunger)` actually means `acex_field_rations_hunger`. Replace your `class acexFood` with my example above and find out the rest of your variable names.

Worry about the thing I wrote about initialization order later.

**Comment by Pyth3rEx** [comment]
so does that mean that GVAR(thirst) = acex_field_rations_thirst and [QEGVAR(medical) = ace_medical_medical ? I'm don't think I understand how to find these variables names.

**Comment by McDiod** [comment]
> so does that mean that GVAR(thirst) = acex_field_rations_thirst

Yes

> and [QEGVAR(medical) = ace_medical_medical ?

No, the EGVAR macro tells you the component directly. `EGVAR(medical,lastDamageSource)` means `ace_medical_lastDamageSource`. 

> I'm don't think I understand how to find these variables names.

You go where you found the variable in the first place. Then look at what is `#include`d at the top of the file, which is usually the file `script_component.hpp`. Then look into that file to find where the component name is defined by `#define COMPONENT componentname`.

**Comment by Pyth3rEx** [comment]
alright, so if I understood everything correctly, using
```
	class customVariables {
        class acexFood {
            varName = "acex_field_rations_hunger";
            varNamespace = "player";
            public = 0;
        };
        class acexWater {
            varName = "acex_field_rations_thirst";
            varNamespace = "player";
            public = 0;
        };
		class aceDamage {
            varName = "ace_medical_lastDamageSource";
            varNamespace = "unit";
            public = 0;
        };
    };
```
should save ACEX food/water + ACE medical state?

**Comment by McDiod** [comment]
> should save ACEX food/water

Might work, yes. If it doesn't, it's probably because ACEX overwrites the variables after they have been loaded. Test it.

> ACE medical state

`lastDamageSource` is just the object that damaged a unit last. You will have to find the variables for limb damage, wounds, pain, blood, treatments, hitpoints, possibly others and save those.

**Comment by DerZade** [comment]
@Pyth3rEx If you're still interested all the macros the ace-project uses are documented (with examples) in their wiki:
https://github.com/gruppe-adler/grad-persistence/issues/24

**Comment by Pyth3rEx** [comment]
so... ace_medical_medical ? WHY IS THIS SO DAMN HARD!!! arg

**Comment by McDiod** [comment]
No, you got the variable name correct, it's `ace_medical_lastDamageSource`.

What I'm saying is you got the wrong variable. Saving that variable won't save a unit's medical state. There is no single variable that will do that. You will have to find all the variables that contain the different parts of a unit's medical state and save those.

**Comment by Pyth3rEx** [comment]
I've been going through the ace github but I can't seem to find anything tough? what am I even looking for?

**Comment by DerZade** [comment]
I guess the `fullHeal` function has to access all the medical variables. So maybe that's a good point to start.

https://github.com/acemod/ACE3/blob/master/addons/medical_treatment/functions/fnc_fullHealLocal.sqf

**Comment by Pyth3rEx** [comment]
ace_medical_bodyPartDamage
ace_medical_
ace_medical_
ace_medical_triageCard

**Comment by Pyth3rEx** [comment]
So that would do the trick right?
```
ace_medical_bodyPartDamage
ace_medical_ivBags
ace_medical_isLimping
ace_medical_occludedMedications
ace_medical_triageCard
```

**Comment by McDiod** [comment]
Also these:

https://github.com/acemod/ACE3/blob/da5e9525b4743631d6a3bc243116e65948364509/addons/medical_engine/script_macros_medical.hpp#L143-L161

**Comment by Pyth3rEx** [comment]
awsome! so I guess I'll just make a custom for each of these?

**Comment by DerZade** [comment]
And after `grad-persistence` has set those variables you probably need to apply them properly by calling the following for each player:
```sqf
[_patient] call ace_medical_engine_updateDamageEffects;
[_patient] call ace_medical_status_updateWoundBloodLoss;
```
(and probably a couple more functions, but now my knowledge of ace's medical systems comes to an end ^^)

**Comment by McDiod** [comment]
I would guess most of these need to be `public = 1`. Namespace "unit" will work for AI. If you want to save it for players, you will need `namespace = "player"`.

**Comment by Pyth3rEx** [comment]
"pply them properly by calling the following for each player:" What exactly do you mean by that? Dosn't gad do everything?

**Comment by DerZade** [comment]
`grad-peristence` just sets the variables, but for ace it's sometimes not enough to just "set the variable". ACE needs to be notified to "apply" them properly.

So just think of it like: You set the player wounds (or similar) and then you have to tell ACE "Yo the guy now has more wounds. Please take them into account when calculating the blood loss!".
If you don't notify ACE it, the guy might not bleed although he has wounds or bleed less / more than he actually should.

**Comment by Pyth3rEx** [comment]
So is that just an ACE thing or does that include ACEX? Also if I understand correctly. I have to add
```
[_patient] call ace_medical_engine_fnc_updateDamageEffects;
[_patient] call ace_medical_status_fnc_updateWoundBloodLoss;
```
into the init.sqf (+ one for each variable?)

**Comment by McDiod** [comment]
> does that include ACEX

Maybe, but probably not. You will have to check ACEX's code to see what needs to happen when variables are updated.

Adding the medical update functions to your init.sqf might work, but it might also be too early. 

I should add an event so that you can execute stuff when the loading is done.

**Comment by Pyth3rEx** [comment]
So here is what I have come up with (so far just taking care of aceX field rations)
init.sqf

**Comment by McDiod** [comment]
grad-persistence already does what you are trying to do here.

What @DerZade meant with "applying variables" was notifying their respective mods that their values have changed. How this works or if this is even necessary has to be checked on a case by case basis in the mods' code.

I suggest you don't worry about it for now and just use the custom variables like we discussed above. Test it and see if it works as expected, then try to troubleshoot once it doesn't.

**Comment by Pyth3rEx** [comment]
Well fact is non of it works currently. I am using the custom variables we have discussed already.

**Comment by Pyth3rEx** [comment]
So ACE food works??? I guess? It just worked... I guess I'll just leave that there and not mind it XD
I can live without medical persistency, all good. thanks for your help!!!
