### ISSUE TITLE
Player inventory persistence broken

### ISSUE THREAD

**Issue by Pyth3rEx** [gruppe-adler/grad-persistence#26]
Player inventory not fully persist. Missing uniform, vest, helmet and GPS.

**Comment by McDiod** [comment]
Can you provide a demo mission?

**Comment by Pyth3rEx** [comment]
The mission I am using is heavly modded. Do you want me to send it anyways?

**Comment by McDiod** [comment]
Put your [cfgGradPersistence](https://github.com/gruppe-adler/grad-persistence/wiki/Configuration) and relevant function calls into an empty mission with just one player unit.

**Comment by Pyth3rEx** [comment]
Find a test mission here.
https://easyupload.io/kvkheu

**Comment by McDiod** [comment]
Just tested this in local multiplayer. Works for me. You are doing `#gradpersistenceSave` yea?

**Comment by Pyth3rEx** [comment]
Yes I am, but even on disconect/reconnect, only a few things save.

**Comment by Pyth3rEx** [comment]
Using this on dedicated multiplayer dosn't work.

**Comment by McDiod** [comment]
Tested it on dedicated now. Works for me also.

**Comment by Pyth3rEx** [comment]
Then I'm confused? I'm using your latest release. What could go wrong?

**Comment by McDiod** [comment]
Have you tested the demo mission that you provided with only cba loaded? It might be some other mod or mission script interfering with the loading.

Try this: Start the mission, then wait for a minute. Open up the debug console and execute this locally:

```
[player,true] call grad_persistence_fnc_loadPlayer
```

If that works, you know everything is being saved correctly, but something during loading fails.
