### ISSUE TITLE
Save location of Data [Question]

### ISSUE THREAD

**Issue by Oldru** [gruppe-adler/grad-persistence#33]
This is something I have wondered for a bit now but, where does grad save the information at?

it can't be in the mission folder as I have deleted a mission and replaced it with an old copy and it loaded the newest save which wasn't available when the older version was copied.

Example of what I am talking about.

1.mission made
2.scripts added - including grad
3.mission tested and saved using grad
4.copy of mission (v0.1) saved and moved away from missions folder
5.mission tested and saved again about 2 hours later - (v0.2)
6. revert to copy due to some *cough cough* mishaps (v0.2) --> (v0.1)
7. old mission (v0.1) tested loading save made 2 hours after this version was saved

**Comment by McDiod** [comment]
grad-persistence saves everything into the server's [profileNamespace](https://community.bistudio.com/wiki/profileNamespace)

> The variables are stored next to the user profile in a file named myUsername.vars.GAMENAME (e.g. in the My Documents\Take On Helicopters folder).

You can delete saves with [grad_persistence_fnc_clearMissionData](https://github.com/gruppe-adler/grad-persistence/wiki/clearMissionData).

**Comment by Oldru** [comment]
Alright so just as a want to know. Is there another way to delete data without using that command?

**Comment by McDiod** [comment]
You can do manually what the function does here to delete specific categories:

https://github.com/gruppe-adler/grad-persistence/blob/master/functions/common/fn_clearMissionData.sqf#L21-L32

**Comment by Oldru** [comment]
thanks for letting me know. I was wondering because other than saying that it saves to the server the wiki never actually says if it saves to the server (server namespace) or the mission (mission namespace). with the exception of the saving variables page, 

https://github.com/gruppe-adler/grad-persistence/wiki/saving-variables

**Comment by Oldru** [comment]
Alright last question before you or I close this, would it be better to erase then save a missions data when saving, deleting the save data after a few saves or just not deleting it at all?

This is a kinda major one because I am about to use grad for a campaign on a server hints why I asked about save location.

**Comment by McDiod** [comment]
Saving completely replaces all previous data that was stored under that [missionTag](https://github.com/gruppe-adler/grad-persistence/wiki/Configuration), so deleting before saving makes no difference.

**Comment by Oldru** [comment]
Alright figured I would ask that as I could see how if it didn't replace all the information it could quickly cause the server or hosted game to go, *mini nuke explosion*
