### ISSUE TITLE
Player position and inventory not saving

### ISSUE THREAD

**Issue by Wiket123** [gruppe-adler/grad-persistence#4]
It looks like most things are saving and loading fine, but the player positions and inventory are not saving. Any idea on how I can fix this? I have configured the description.ext.

**Comment by Wiket123** [comment]
Here is the hole mission file

[101stMissionTest.Baranow.zip](https://github.com/gruppe-adler/grad-persistence/files/2682440/101stMissionTest.Baranow.zip)

**Comment by Wiket123** [comment]
So do I just remove that from the description?

**Comment by McDiod** [comment]
yes

**Comment by McDiod** [comment]
I can't test your mission, because of the dependencies to your modset, but here is an example that works:
[grad-persistence_exampleMission1.Stratis.zip](https://github.com/gruppe-adler/grad-persistence/files/2682971/grad-persistence_exampleMission1.Stratis.zip)
