### ISSUE TITLE
The clearMissionData Function

### ISSUE THREAD

**Issue by HentiSenpai** [gruppe-adler/grad-persistence#40]
Hello,

Not being very experienced with scripting, I've managed to get the persistence to work with saving and loading, however I am not sure how to use this function. I have read the wiki page on function but it doesn't specifically say where to put it. Does it go in the description.ext or somewhere else? Any help would be greatly appreciated.

Thank you.

**Comment by McDiod** [comment]
It's mostly intended to be used from the [debug console](https://community.bistudio.com/wiki/Arma_3:_Debug_Console(. Put it into the big expression field up top and hit the execute on server button.

**Comment by HentiSenpai** [comment]
It seems to be working, thank you very much.
