### ISSUE TITLE
Is there anyway to blacklist arrays saving?

### ISSUE THREAD

**Issue by TenuredCLOUD** [gruppe-adler/grad-persistence#47]
As title said I'd like to blacklist some spawning arrays from GRAD so GRAD doesn't save the items that are spawned, is this possible? Or do I need to list the objects as shown in the example description.ext?

Example array:

`VD_CS_Wrecks = ["Land_Wreck_Heli_Attack_01_F","Land_Wreck_Heli_Attack_02_F","Land_UWreck_MV22_F","Mi8Wreck","BlackhawkWreck"];`

Example in wiki:

`[_objectname] call grad_persistence_fnc_blacklistObjects;`

For this I'd put:

`[VD_CS_Wrecks] call grad_persistence_fnc_blacklistObjects;`

^^?

listed Array EX:

`["VD_CS_Wrecks","VD_BC_Spawner"] call grad_persistence_fnc_blacklistObjects;`

Are these correct / possible with GRAD?

Thank you for your time

**Comment by McDiod** [comment]
As far as I can tell you want to blacklist every object of a specific class, so you will need [grad_persistence_fnc_blacklistclasses](https://github.com/gruppe-adler/grad-persistence/wiki/blacklisting#grad_persistence_fnc_blacklistclasses). So
 ```
VD_CS_Wrecks call grad_persistence_fnc_blacklistclasses;
```

If you want to easily blacklist multiple arrays, use
```
{_x call grad_persistence_fnc_blacklistclasses} forEach [
    VD_CS_Wrecks,
    VD_BC_Spawner,
    ...
];
```

**Comment by TenuredCLOUD** [comment]
Thank you very much for the quick response! 

Sorry for the delayed reaction but thumbs up! 

Closing this :) 🍻
