### ISSUE TITLE
[question]: Are entity variables (via setVariable) are also be saved?

### ISSUE THREAD

**Issue by svencc** [gruppe-adler/grad-persistence#53]
Are Entity Attributes (via setAttribute) are also be saved?
Or do I have to persist those Information via global variables?

**Comment by McDiod** [comment]
`set3DENAttribute`? No, these are not saved by default. There is also no easy way to restore them on mission load, because there are no events fired by grad-fortification, that you could hook into.

**Comment by svencc** [comment]
@McDiod 
Sorry my mistake! 

I meant the variables which are set/get via setVariable/getVariable.

**Comment by McDiod** [comment]
Those are supported (see [saving variables](https://github.com/gruppe-adler/grad-persistence/wiki/Saving-Variables) in the Wiki).

So e.g. if you are using `this setVariable ["svencc_soldierIsCool",false,true]` on an AI soldier, you have to create a grad-persistence variable config with namespace "unit".

**Comment by svencc** [comment]
So I need to configure those CfgGradPersistence class and need to add each single variable which do exist on any Unit?

class CfgGradPersistence {
    class customVariables {
        class var1 {
            varName = "isHVT";   <-- this name needs to be the same as the actual variable name on an entity?
            varNamespace = "unit";
            public = 1;
        };
    };
};


In the above example: Will the variable "anyUnit setVariable["isHVT",true]" be persisted on ALL units?

**Comment by McDiod** [comment]
> So I need to configure those CfgGradPersistence class and need to add each single variable which do exist on any Unit?

yes

> ```
>             varName = "isHVT";   <-- this name needs to be the same as the actual variable name on an entity?
> ```

yes

> In the above example: Will the variable "anyUnit setVariable["isHVT",true]" be persisted on ALL units (which have this variable set)?

All AI units, yes. For player units, use `varNamespace = "player";`. Also make sure the variable you want to save is known to the server.

**Comment by svencc** [comment]
Thanks a lot!

Can I find you on the GRUPPE ADLER discord?

**Comment by nomisum** [comment]
> Thanks a lot!
> 
> Can I find you on the GRUPPE ADLER discord?

yes, McDiod#9647
