### ISSUE TITLE
Configuration "loadOnMissionStart" default value does not match documentation

### ISSUE THREAD

**Issue by jmlane** [gruppe-adler/grad-persistence#55]
The [configuration documentation for the default value of `loadOnMissionStart`](https://github.com/gruppe-adler/grad-persistence/wiki/Configuration#general-settings) (`1`) doesn't match the default value returned from `BIS_fnc_returnConfigEntry` for that configuration key (`0`): https://github.com/gruppe-adler/grad-persistence/blob/master/functions/common/fn_initModule.sqf#L31

Thanks!

**Comment by McDiod** [comment]
Corrected. Thanks for the report 👍
